// Automatically generated by flapigen
package org.dashj.dpp;


public final class ProtocolVersion {

    public ProtocolVersion() {
        mNativeObj = init();
    }
    private static native long init();

    public final long get_protocol_version() {
        long ret = do_get_protocol_version(mNativeObj);

        return ret;
    }
    private static native long do_get_protocol_version(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ProtocolVersion(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}