cargo-features = ["profile-rustflags"]
[package]
name = "dashj-dpp-bindings"
version = "0.25.0"
authors = ["HashEngineering <hashengineeringsolutions@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = { version = "0.5", default-features = false }
hex = { version = "0.3.0" }
quote = { version = "1.0.26"}
dpp = { git = "https://github.com/dashpay/platform.git", branch = "v0.25-dev", features = ["cbor"], default-features = false }
platform-value = { git = "https://github.com/dashpay/platform.git", branch = "v0.25-dev", default-features = false }


[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
#opt-level = "z"  # or any other optimization level you prefer
#panic = "abort"  # or "unwind" if you want unwinding panics
debug = false    # set to true if you want debug symbols in release builds
rustflags = ["-C", "link-args=-fPIC"]
